"""add_performance_indexes

Revision ID: 42de0e178841
Revises: f21408640952
Create Date: 2026-07-18 03:57:19.525489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42de0e178841'
down_revision: Union[str, Sequence[str], None] = 'f21408640952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_position'), 'albums', ['position'], unique=False)
    op.create_index(op.f('ix_scrollytelling_chapters_position'), 'scrollytelling_chapters', ['position'], unique=False)
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    op.create_index(op.f('ix_songs_track_number'), 'songs', ['track_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_track_number'), table_name='songs')
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.drop_index(op.f('ix_scrollytelling_chapters_position'), table_name='scrollytelling_chapters')
    op.drop_index(op.f('ix_albums_position'), table_name='albums')
    # ### end Alembic commands ###
