"""Initial schema with chapters

Revision ID: f21408640952
Revises:
Create Date: 2026-07-16 07:18:36.770715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f21408640952'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cover', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('genre_tags', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_table('scrollytelling_chapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('chapter_label', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('eyebrow', sa.String(), nullable=False),
    sa.Column('stat_number', sa.String(), nullable=True),
    sa.Column('stat_label', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrollytelling_chapters_id'), 'scrollytelling_chapters', ['id'], unique=False)
    op.create_table('site_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('lyrics', sa.Text(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_scrollytelling_chapters_id'), table_name='scrollytelling_chapters')
    op.drop_table('scrollytelling_chapters')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
